Nome = str(input("Digite seu nome: "))
print ("Digite sua CPF:")
Cpf = str(input())
print ("Digite seu telefone:")
Telefone = str(input())
print ("Digite seu ano de nascimento:")
Nascimento = str(input())
print("Seus dados:")
print("Nome: " + Nome)
print("Cpf: " + Cpf)
print("Telefone: " + Telefone)
print("Telefone: " + Nascimento)
print ("Digite seu peso:")
Peso = float(input())
print ("Digite sua altura:")
Altura = float(input())
Imc = str(Peso/(Altura * Altura))
print ("Imc: " + Imc)
